services:
  postgresql:
    image: postgres:16.8
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: service
      POSTGRES_PASSWORD: "abcD123"
      TZ: "Asia/Tokyo" # TODO データベースに反映されない原因を要調査。
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 100s
    volumes:
      - ./docker/db/entrypoints:/docker-entrypoint-initdb.d

  db_builder:
    build:
      context: ./docker/db/builder
    environment:
      PGPASSWORD: "abcD123" # psql コマンドでパスワード入力を省略するため。
    depends_on:
      postgresql:
        condition: service_healthy

